export const ptBR = {
  variables: {
    sign_in: {
      email_label: 'E-mail',
      email_input_placeholder: 'Seu e-mail',
      password_label: 'Senha',
      password_input_placeholder: 'Sua senha',
      button_label: 'Entrar',
      loading_button_label: 'Entrando...',
      social_provider_text: 'Entrar com {{provider}}',
      link_text: 'Não tem conta? Cadastre-se',
      // Alguns temas usam esta chave para o link de esqueci a senha
      forgot_password_link_text: 'Esqueceu sua senha?',
    },
    sign_up: {
      email_label: 'E-mail',
      email_input_placeholder: 'Seu e-mail',
      password_label: 'Crie uma senha',
      password_input_placeholder: 'Sua senha',
      button_label: 'Criar conta',
      loading_button_label: 'Criando conta...',
      social_provider_text: 'Cadastrar com {{provider}}',
      link_text: 'Já tem uma conta? Entrar',
    },
    forgot_password: {
      email_label: 'Digite seu e-mail para redefinir a senha',
      button_label: 'Enviar instruções de redefinição',
      loading_button_label: 'Enviando...',
      link_text: 'Esqueceu sua senha?',
      confirmation_text: 'Verifique seu e-mail para redefinir a senha',
    },
    magic_link: {
      email_input_label: 'E-mail',
      email_input_placeholder: 'Seu e-mail',
      button_label: 'Enviar link mágico',
      loading_button_label: 'Enviando link mágico...',
      link_text: 'Entrar com link mágico',
      link_sent_text: 'Verifique seu e-mail para o link mágico',
    },
    update_password: {
      password_label: 'Nova senha',
      password_input_placeholder: 'Sua nova senha',
      button_label: 'Atualizar senha',
      loading_button_label: 'Atualizando...',
      password_mismatch_error: 'As senhas não coincidem',
    },
    verify_otp: {
      email_input_label: 'E-mail',
      email_input_placeholder: 'Seu e-mail',
      phone_input_label: 'Telefone',
      phone_input_placeholder: 'Seu telefone',
      token_input_label: 'Código',
      token_input_placeholder: 'Digite o código recebido',
      button_label: 'Confirmar',
      loading_button_label: 'Confirmando...',
    },
  },
};